### ISSUE TITLE
许多应用上报后不显示

### ISSUE THREAD

**Issue by YuziO2** [TNXG/ProcessReporterWinpy#2]
例如chrome，微信，网易云音乐等不会显示。
会显示的应用有：vscode，Windows terminal，explorer
音乐播放显示正常。

**Comment by TNXG** [comment]
目前只支持显示`https://github.com/Innei/Shiro/blob/main/src/components/layout/header/internal/Activity.tsx`中存在的程序（可以选择Pr，

部分程序在Windows、Linux、MacOS中进程名称都不相同，以在`Activity.tsx`中保存的为准，可以在配置项中选择替换，关于这一方面请仔细阅读[README.MD#配置项](https://github.com/TNXG/ProcessReporterWinpy#%E9%85%8D%E7%BD%AE%E9%A1%B9)，

不在Shiro中显示的则为Shiro尚未添加的软件，ProcessReporter只负责上报进程名称，显示问题交给Shiro处理

Over

**Comment by TNXG** [comment]
Timeout Close
