### ISSUE TITLE
大佬，有办法获取洛雪的播放信息吗？

### ISSUE THREAD

**Issue by rebron1900** [TNXG/ProcessReporterWinpy#7]
平时都是用这个听歌的。

**Comment by TNXG** [comment]
我们支持全部能够通过WindowsRuntime SystemMediaTransportControls显示播放信息流的软件，其他不遵守SystemMediaTransportControls可以通过其他行为方式进行适配，Pr welcome

**Comment by rebron1900** [comment]
洛雪原生支持，打扰了

**Comment by rebron1900** [comment]
另外在使用其他播放器时，似乎不会附带media播放程序的信息。

**Comment by TNXG** [comment]
> 洛雪原生支持，打扰了

如果支持SystemMediaTransportControls也可以去尝试使用Golang编写的[**ProcessReporterWingo**](https://github.com/TNXG/ProcessReporterWingo)

**Comment by TNXG** [comment]
> 另外在使用其他播放器时，似乎不会附带media播放程序的信息。

需要播放器原生支持SystemMediaTransportControls，如果不支持的话只能通过别的方法获取（网易云音乐和QQ音乐都是这样的，目前只适配了网易云音乐的样子）

**Comment by rebron1900** [comment]
> > 另外在使用其他播放器时，似乎不会附带media播放程序的信息。
> 
> 需要播放器原生支持SystemMediaTransportControls，如果不支持的话只能通过别的方法获取（网易云音乐和QQ音乐都是这样的，目前只适配了网易云音乐的样子）

我的意思不会附带是什么播放器，🤔
![image](https://github.com/TNXG/ProcessReporterWinpy/assets/7929884/152b2260-bb76-4cd7-afd5-c4d246c25f14)

**Comment by rebron1900** [comment]
go版的似乎会附带播放器信息，感谢大佬！

**Comment by TNXG** [comment]
> > > 另外在使用其他播放器时，似乎不会附带media播放程序的信息。
> > 
> > 
> > 需要播放器原生支持SystemMediaTransportControls，如果不支持的话只能通过别的方法获取（网易云音乐和QQ音乐都是这样的，目前只适配了网易云音乐的样子）
> 
> 我的意思不会附带是什么播放器，🤔 ![image](https://private-user-images.githubusercontent.com/7929884/329583059-152b2260-bb76-4cd7-afd5-c4d246c25f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNDYzMDEsIm5iZiI6MTcxNTM0NjAwMSwicGF0aCI6Ii83OTI5ODg0LzMyOTU4MzA1OS0xNTJiMjI2MC1iYjc2LTRjZDctYWZkNS1jNGQyNDZjMjVmMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTBUMTMwMDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM4MmMwZGVjOGU0MWMwNDBiOGI0OTk5YWYzZjBjNjI5NDJkMDNhYjcxNzdlNGIzYmVhNjlhNmUwMTRiYzYxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ErOEApIDTMu1fNrpusejTnG3Fb9P6CKut4kbtKwnsJY)

媒体上报只上报艺术家和曲名，程序上报是前台运行程序
